image: atlassian/default-image:latest

pipelines:
  default:
    # - step:
    #     name: Trivy Scan Source Code
    #     script:
    #       - echo "Installing Trivy..."
    #       - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

    #       - echo "Scanning source code (filesystem)..."
    #       # - trivy fs . --exit-code 1 --severity HIGH,CRITICAL --format table

    #       - echo "Generating SBOM (CycloneDX)..."
    #       - mkdir -p reports
    #       - trivy fs . --format cyclonedx -o reports/sbom.cdx.json

    #     artifacts:
    #       - reports/**
    - step:
        name: Docker Build & Trivy Image Scan
        image: docker:24.0.7
        services:
          - docker
        caches:
          - docker
        script:
          - echo "Installing Trivy..."
          - apk add --no-cache curl
          - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

          - echo "Building Docker image..."
          - export DOCKER_BUILDKIT=0  
          - docker build -t my-app-image .

          - echo "Scanning Docker image..."
          # - trivy image my-app-image --exit-code 1 --severity HIGH,CRITICAL --format table

          # - echo "Generating SBOM from image..."
          - mkdir -p reports
          # - trivy image my-app-image --format cyclonedx -o reports/sbom-image.cdx.json
          - trivy image my-app-image --format json -o reports/image-report.json

        artifacts:
          - reports/**










    - step:
        name: Upload to S3 using OIDC
        image: amazon/aws-cli 
        oidc: true
        script:
          - export AWS_REGION=$AWS_DEFAULT_REGION 
          - export AWS_ROLE_ARN=$AWS_OIDC_ROLE_ARN
          - export AWS_WEB_IDENTITY_TOKEN_FILE=$(pwd)/web-identity-token
          - echo $BITBUCKET_STEP_OIDC_TOKEN > $(pwd)/web-identity-token

          - export BUILD_NUM=$BITBUCKET_BUILD_NUMBER
          
          - aws s3 cp reports/image-report.json s3://$S3_BUCKET_NAME/image-report-${BUILD_NUM}.json
          - aws s3 cp reports/sbom.cdx.json s3://$S3_BUCKET_NAME/sbom-${BUILD_NUM}.cdx.json


definitions:
  services:
    docker:
      memory: 1024 






