services:
  app:
    build: 
    container_name: 
    ports:
      - 
    env_file:
      - 
    networks:
      - 
    restart: always
    mem_limit: "2G"
    cpus: "2.00"
 
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]  
      interval: 30s
      timeout: 10s
      retries: 3
networks:
  cyber-app-network:
    driver: bridge 